[package]
name = "pure-ts"
version = "0.1.0"
edition = "2024"

[dependencies]
oxc_parser = "0.30.0"
oxc_ast = "0.30.0"
oxc_span = "0.30.0"
oxc_allocator = "0.30.0"
oxc_diagnostics = "0.30.0"
oxc_syntax = "0.30.0"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
glob = "0.3"
colored = "2.1"
